spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/iot_devices
    username: root
    password: Jenisha@123
    driver-class-name: com.mysql.cj.jdbc.Driver
     
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history
    clean-disabled: true # Safety measure!
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all  # Ensure message is written to all replicas
      retries: 3  # Number of retries for failed sends
      batch-size: 16384  # 16KB batch size
      buffer-memory: 33554432  # 32MB buffer memory
      linger-ms: 20  # Wait up to 20ms to batch messages
    consumer:
      group-id: iot-device-group  # Consumer group ID
      auto-offset-reset: earliest  # Read from beginning if no offset
      enable-auto-commit: false  # Manual commit
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 500  # Max records per poll
      fetch-max-wait-ms: 500  # Max wait time for fetch
      fetch-min-size: 1  # Minimum bytes to fetch

# Kafka Topics Configuration
kafka:
  topics:
    device-events: thingwire.devices.events
    device-commands: thingwire.devices.commands
    device-responses: thingwire.devices.responses

server:
  port: 8084

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 864000000
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always  # Show full details unconditionally
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
  show-actuator: true
logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    com.example.iot: DEBUG
    

    